// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"KRD_MZ_Dice","status":true,"description":"サイコロを振り、結果を変数に入れます。","parameters":{"swRolling":"1","varDice":"6","plusX":"0","plusY":"0"}},
{"name":"AltMenuScreen","status":true,"description":"Alternative menu screen layout.","parameters":{}},
{"name":"AltSaveScreen","status":true,"description":"Alternative save/load screen layout.","parameters":{}},
{"name":"ButtonPicture","status":true,"description":"Makes a picture clickable.","parameters":{}},
{"name":"TextPicture","status":true,"description":"Displays text as a picture.","parameters":{}},
{"name":"NPCProfitLabel","status":true,"description":"在事件/NPC頭上顯示「文字標籤 + 指定變數數值」，可用於顯示理財獲利 v2.1","parameters":{"showSwitchId":"30","fontSize":"24","offsetY":"-70","showZero":"true","textWidth":"240"}},
{"name":"ForceStretch","status":true,"description":"強制網頁版遊戲自動延展填滿可用空間（適合 iframe / 平板橫向）","parameters":{}},
{"name":"PlayerLogger","status":true,"description":"玩家行為紀錄系統（本機寫檔 / 網頁 localStorage / 可匯出）v1.2","parameters":{}}
];
